version: '3.8'
services:
  birthday-commander-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb_tests
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres_data/data

volumes:
  postgres_data: